// <auto-generated />
using System;
using CoDodoApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoDodoApi.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302222654_ModelUpdates")]
    partial class ModelUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Opportunities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capability");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("HourlyRateInSek")
                        .HasColumnType("numeric")
                        .HasColumnName("hourly_rate_in_sek");

                    b.Property<string>("NameOfSalesLead")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_of_sales_lead");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UriForAssignment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri_for_assignment");

                    b.HasKey("Id")
                        .HasName("pk_opportunities");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunities_id");

                    b.HasIndex("UriForAssignment")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunities_uri_for_assignment");

                    b.ToTable("opportunities", (string)null);
                });

            modelBuilder.Entity("Domain.Processes.Process", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OpportunityUri")
                        .HasColumnType("text")
                        .HasColumnName("opportunity_uri");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Name", "OpportunityUri")
                        .HasName("pk_processes");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_processes_opportunity_id");

                    b.ToTable("processes", (string)null);
                });

            modelBuilder.Entity("Domain.Processes.Process", b =>
                {
                    b.HasOne("Domain.Opportunities.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processes_opportunities_opportunity_id");

                    b.Navigation("Opportunity");
                });
#pragma warning restore 612, 618
        }
    }
}
