// <auto-generated />
using System;
using CoDodoApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoDodoApi.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoDodoApi.Database.Entities.Opportunity", b =>
                {
                    b.Property<string>("UriForAssignment")
                        .HasColumnType("text")
                        .HasColumnName("uri_for_assignment");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capability");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<int>("HourlyRateInSEK")
                        .HasColumnType("integer")
                        .HasColumnName("hourly_rate_in_sek");

                    b.Property<string>("NameOfSalesLead")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_of_sales_lead");

                    b.HasKey("UriForAssignment")
                        .HasName("pk_opportunities");

                    b.HasIndex("UriForAssignment")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunities_uri_for_assignment");

                    b.ToTable("opportunities", (string)null);
                });

            modelBuilder.Entity("CoDodoApi.Database.Entities.Process", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OpportunityUri")
                        .HasColumnType("text")
                        .HasColumnName("opportunity_uri");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Name", "OpportunityUri")
                        .HasName("pk_processes");

                    b.HasIndex("OpportunityUri")
                        .HasDatabaseName("ix_processes_opportunity_uri");

                    b.ToTable("processes", (string)null);
                });

            modelBuilder.Entity("CoDodoApi.Database.Entities.Process", b =>
                {
                    b.HasOne("CoDodoApi.Database.Entities.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityUri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processes_opportunities_opportunity_uri");

                    b.Navigation("Opportunity");
                });
#pragma warning restore 612, 618
        }
    }
}
